#include <stdio.h>

int main(int argc, char *argv[])
{
	printf
	(
	  "#ifndef LIB65816_CONFIG_H\n"
	  "#define LIB65816_CONFIG_H\n"
	  "/* DO NOT MODIFY THIS FILE; THIS FILE IS AUTOMATICALLY GENERATED. */\n\n"
	  "#define SIZEOF_LONG  %ld\n"
	  "#define SIZEOF_INT   %ld\n"
	  "#define SIZEOF_SHORT %ld\n"
	  "#define DEBUG        1\n"
	  "#endif\n"

	, sizeof(long)
	, sizeof(int)
	, sizeof(short)
	);

	return 0;
}

